name: eslint-check
on:
  push:
    branches:
      - develop
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm ci
      - name: ESLint
        run: npx eslint *.js